{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    concatMapStringsSep
    concatStringsSep
    optionals
    intersperse
    filter
    mapAttrsToList
    mkIf
    mkOption
    optional
    types
    ;

  cfg = config.programs.imapgoose;

  # Filter to ONLY the accounts that have imapgoose enabled
  imapgooseAccounts = filter (a: a.enable && a.imapgoose.enable) (
    lib.attrValues config.accounts.email.accounts
  );

  genValue =
    v:
    if lib.isList v then
      concatStringsSep " " (map toString v)
    else if lib.isBool v then
      (if v then "true" else "false")
    else
      toString v;
in
{

  meta.maintainers = [ lib.maintainers.philocalyst ];

  options = {
    programs.imapgoose = {
      enable = lib.mkEnableOption "synchronization using ImapGoose" // {
        default = false;
      };

      package = lib.mkPackageOption pkgs "imapgoose" { };

      extraConfig = mkOption {
        type = types.lines;
        default = "";
        description = ''
          Extra configuration lines to append to the end of the ImapGoose configuration file.
        '';
      };
    };

    accounts.email.accounts = mkOption {
      type = with types; attrsOf (submodule (import ./accounts.nix));
    };
  };

  config = mkIf cfg.enable (
    let
      genAccountConfig =
        acc:
        let
          port = if acc.imap.port != null then acc.imap.port else (if acc.imap.tls.enable then 993 else 143);
          lines = [
            "account ${acc.name} {"
            "	server ${acc.imap.host}:${toString port}"
            "	username ${acc.userName}"
            "	password-cmd ${toString acc.passwordCommand}"
            "	local-path ${acc.maildir.absPath}"
          ]
          ++ optional (
            acc.imapgoose.maxConnections != null
          ) "	max-connections ${toString acc.imapgoose.maxConnections}"
          ++ optional (acc.imapgoose.postSyncCmd != null) "	post-sync-cmd ${acc.imapgoose.postSyncCmd}"
          ++ mapAttrsToList (k: v: "	${k} ${genValue v}") acc.imapgoose.extraConfig
          ++ [ "}" ];
        in
        concatStringsSep "\n" lines;
    in
    {
      assertions =
        let
          checkAccounts =
            pred: msg:
            let
              badAccounts = filter pred imapgooseAccounts;
            in
            {
              assertion = badAccounts == [ ];
              message = "imapgoose: ${msg} for accounts: " + concatMapStringsSep ", " (a: a.name) badAccounts;
            };
        in
        [
          (checkAccounts (a: a.maildir == null) "Missing maildir configuration")
          (checkAccounts (a: a.imap == null) "Missing IMAP configuration")
          (checkAccounts (a: a.passwordCommand == null) "Missing passwordCommand")
          (checkAccounts (a: a.userName == null) "Missing username")
        ];

      home.packages = [ cfg.package ];

      xdg.configFile."imapgoose/config.scfg".text = concatStringsSep "\n" (
        [ "# Generated by Home Manager." ]
        ++ optionals (imapgooseAccounts != [ ]) (
          [ "" ] ++ intersperse "" (map genAccountConfig imapgooseAccounts)
        )
        ++ optionals (cfg.extraConfig != "") [
          ""
          cfg.extraConfig
          ""
        ]
      );

      home.activation = mkIf (imapgooseAccounts != [ ]) {
        createImapgooseMaildir = lib.hm.dag.entryBetween [ "linkGeneration" ] [ "writeBoundary" ] ''
          $DRY_RUN_CMD mkdir -m700 -p $VERBOSE_ARG ${
            concatMapStringsSep " " (a: lib.escapeShellArg a.maildir.absPath) imapgooseAccounts
          }
        '';
      };
    }
  );
}
