#!/nix/store/00000000000000000000000000000000-bash/bin/bash


herbstclient emit_hook reload

# Reset everything.
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.floating.reset 1
herbstclient keyunbind --all
herbstclient mouseunbind --all
herbstclient unrule --all













herbstclient unlock



