# Tests for the activation snippet generated by mkImpureConfigMerger. It is
# run the way home activation runs it: as a script with the home-manager bash
# helpers available, against files in a temporary home.
{
  lib,
  pkgs,
  ...
}:

let
  mkMerger =
    format: static:
    lib.hm.generators.mkImpureConfigMerger {
      inherit pkgs format;
      empty = "{}";
      jqOperation = "$dynamic * $static";
      path = "/@TMPDIR@/hm-user/.config/testmerger/settings.${format}";
      staticSettings = builtins.toFile "static-settings.${format}" static;
    };

  # Mirror the activation script environment: set -euo pipefail is active and
  # home-manager.sh provides errorEcho.
  mkScript =
    name: snippet:
    pkgs.writeScript name ''
      set -euo pipefail
      errorEcho() { echo "$*" >&2; }
      ${snippet}
    '';

  mergeJson = mkScript "merge-json" (mkMerger "json" (builtins.toJSON { nixManaged = true; }));
  mergeToml = mkScript "merge-toml" (mkMerger "toml" "nixManaged = true\n");

  # jaq prints the first object of this stream before failing on the
  # truncated second one, so checking only the reader output would accept a
  # partial read.
  truncatedJson = builtins.toFile "truncated.json" ''
    {"keep":true}
    {"lost":
  '';

  userToml = builtins.toFile "user.toml" ''
    userSetting = 5
  '';

  expectedJson = builtins.toFile "expected.json" ''
    {
      "nixManaged": true
    }
  '';

  expectedToml = builtins.toFile "expected.toml" ''
    nixManaged = true
  '';

  expectedUserToml = builtins.toFile "expected-user.toml" ''
    userSetting = 5
    nixManaged = true
  '';
in
{
  nmt.script = ''
    substitute ${mergeJson} $TMPDIR/merge-json --subst-var TMPDIR
    substitute ${mergeToml} $TMPDIR/merge-toml --subst-var TMPDIR
    chmod +x $TMPDIR/merge-json $TMPDIR/merge-toml

    mkdir -p $TMPDIR/hm-user/.config/testmerger
    jsonSettings=$TMPDIR/hm-user/.config/testmerger/settings.json
    tomlSettings=$TMPDIR/hm-user/.config/testmerger/settings.toml

    # A reader that emits JSON before failing must fail activation and keep
    # the original file instead of merging the partial output.
    cat ${truncatedJson} > $jsonSettings
    if $TMPDIR/merge-json > /dev/null 2>&1; then
      fail "Merging a truncated JSON stream must fail activation"
    fi
    assertFileContent $jsonSettings ${truncatedJson}

    # A missing JSON target installs the generated settings.
    rm -f $jsonSettings
    $TMPDIR/merge-json
    assertFileContent $jsonSettings ${expectedJson}

    # A missing TOML target installs the generated settings instead of
    # failing on a file seeded with the JSON `empty` value.
    $TMPDIR/merge-toml
    assertFileContent $tomlSettings ${expectedToml}

    # Existing user settings survive the merge.
    cat ${userToml} > $tomlSettings
    $TMPDIR/merge-toml
    assertFileContent $tomlSettings ${expectedUserToml}

    # A zero-byte file is treated as `empty`.
    : > $tomlSettings
    $TMPDIR/merge-toml
    assertFileContent $tomlSettings ${expectedToml}
  '';
}
