disabled = [
  "bool_comparison",
  "bool_simplification",
  "collapsible_let_in",
  "deprecated_is_null",
  "deprecated_to_path",
  "empty_list_concat",
  "empty_inherit",
  "empty_let_in",
  "empty_pattern",
  "eta_reduction",
  "faster_groupby",
  "faster_zipattrswith",
  "legacy_let_syntax",
  "repeated_keys",
  "redundant_pattern_bind",
  "unquoted_uri",
  "useless_has_attr",
  "useless_parens",
]
