{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.afew;
  configFile = ''
    # Generated by Home Manager.
    # See https://afew.readthedocs.io/en/latest/index.html

    ${cfg.extraConfig}
  '';
in
{
  options.programs.afew = {
    enable = mkEnableOption "the Afew initial tagging script for Notmuch";

    extraConfig = mkOption {
      type = types.lines;
      default = ''
        [SpamFilter]
        [KillThreadsFilter]
        [ListMailsFilter]
        [ArchiveSentMailsFilter]
        [InboxFilter]
      '';
      example = ''
        # see more examples at https://afew.readthedocs.io/en/latest/configuration.html
        [SpamFilter]

        [Filter.0]
        query = from:pointyheaded@boss.com
        tags = -new;+boss
        message = Message from above

        [InboxFilter]
      '';
      description = ''
        Extra lines added to afew configuration file.
      '';
    };

  };
  config = mkIf cfg.enable {
    home.packages = [ pkgs.afew ];
    xdg.configFile."afew/config".text = configFile;
  };
}
