{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.libreoffice;
  xcuPath = "libreoffice/4/user/registrymodifications.xcu";
  ooSetupPath = "/org.openoffice.Setup/Product";
  ooSetupKey = "ooSetupLastVersion";
  toValue =
    input:
    if lib.isBool input then
      # `lib.toString` yields an empty string for `false` and "1" for true by
      # default; use `lib.boolToString` to return "true" and "false" directly.
      lib.boolToString input
    else
      lib.toString input;
in
{
  meta.maintainers = lib.attrValues {
    inherit (lib.maintainers)
      ekhh
      ;
  };

  options.programs.libreoffice = {
    enable = lib.mkEnableOption "LibreOffice, a comprehensive office suite.";
    package = lib.mkPackageOption pkgs "libreoffice-fresh" {
      nullable = true;
      example = "pkgs.libreoffice-still";
    };
    settings = lib.mkOption {
      default = { };
      type = lib.types.attrsOf lib.types.anything;
      example = {
        "/org.openoffice.Office.Common/Filter/PDF/Export" = {
          PDFUACompliance = true;
          SelectPdfVersion = 4;
        };
      };
      description = ''
        Configuration written to {file}`$XDG_CONFIG_HOME/${xcuPath}`.

        Available options are documented as tooltips in the `Expert
        Configuration` dialog.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      (lib.hm.assertions.assertPlatform "programs.libreoffice" pkgs lib.platforms.linux)
      {
        assertion =
          (cfg.settings ? ${ooSetupPath} && cfg.settings.${ooSetupPath} ? ${ooSetupKey})
          || cfg.settings == { }
          || cfg.package != null;
        message = "`\"${ooSetupPath}\".${ooSetupKey}` must be set in `programs.libreoffice.settings` if `package` is unset.";
      }
    ];
    home.packages = lib.mkIf (cfg.package != null) [ cfg.package ];
    # `builtins.toXML` has various issues and may be deprecated in the future;
    # see <https://github.com/NixOS/nix/issues/15745#issue-4334624253>.
    xdg.configFile.libreoffice-configuration = lib.mkIf (cfg.settings != { }) {
      text = ''
        <?xml version="1.0" encoding="UTF-8"?>
        <!-- Generated by Home Manager. -->
        <oor:items xmlns:oor="http://openoffice.org/2001/registry" ''
      + ''xmlns:xs="http://www.w3.org/2001/XMLSchema" ''
      + ''xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">''
      + "\n"
      +
        lib.concatMapAttrsStringSep ""
          (
            path: attrs:
            lib.concatMapAttrsStringSep "" (
              name: value:
              lib.optionalString (toValue value != "") (
                /*
                  IMPORTANT: apply `lib.escapeXML` on everything. The
                  `givenname` field, for instance, accepts a string input; if
                  not escaped, an ampersand in a company's name is alone
                  sufficient to invalidate the configuration file.
                */
                ''<item oor:path="${lib.escapeXML path}">''
                + ''<prop oor:name="${lib.escapeXML name}" oor:op="fuse">''
                + "<value>${lib.escapeXML (toValue value)}</value>"
                + "</prop></item>\n"
              )
            ) attrs
          )
          (
            lib.recursiveUpdate (lib.optionalAttrs (cfg.package != null) {
              ${ooSetupPath}.${ooSetupKey} =
                /*
                  This value records the last major version (xx.xx) whereupon a
                  setup was run. The configuration will be ignored if it is
                  absent.
                */
                lib.head (lib.match "^([^.]+[.][^.]+).*" cfg.package.version);
            }) cfg.settings
          )
      + "</oor:items>\n";
      target = xcuPath;
    };
  };
}
