-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm';
return {
  font = wezterm.font("JetBrains Mono"),
  font_size = 16.0,
  color_scheme = "Tomorrow Night",
  hide_tab_bar_if_only_one_tab = true,
  default_prog = { "zsh", "--login", "-c", "tmux attach -t dev || tmux new -s dev" },
  keys = {
    {key="n", mods="SHIFT|CTRL", action="ToggleFullScreen"},
  }
}

