{ ... }:

{
  programs.wezterm = { enable = true; };

  test.stubs.wezterm = { };

  nmt.script = let
    expected = builtins.toFile "wezterm.lua" ''
      -- Generated by Home Manager.
      -- See https://wezfurlong.org/wezterm/

      local wezterm = require 'wezterm'

      return {}

    '';
  in ''
    assertFileExists home-files/.config/wezterm/wezterm.lua
    assertFileContent home-files/.config/wezterm/wezterm.lua ${expected}
  '';
}
