-- Generated by Home Manager.

local wezterm = require("wezterm")

return {
  -- Keybinds
  keys = {
    {
      key = "l",
    },
    {
      key = "l",
      action = wezterm.action {ActivateTabRelative = 1},
    },
    {
      mods = "SHIFT|CTRL",
      key = "h",
      action = wezterm.action {ActivateTabRelative = -1},
    },
  },

  

  

  -- Colors
  colors = {
    foreground = "#C0C0C0",
    background = "#000000",
    cursor_bg = "#52AD70",
    cursor_fg = "#000000",
    cursor_border = "#52AD70",
    selection_bg = "#FFFACD",
    selection_fg = "#000000",
    scrollbar_thumb = "#222222",
    split = "#444444",
    ansi = { "#000000", "#000080", "#008080", "#008000", "#800080", "#800000", "#C0C0C0", "#808000" },
    brights = { "#808080", "#0000FF", "#00FFFF", "#00FF00", "#FF00FF", "#FF0000", "#FFFFFF", "#FFFF00" },
    tab_bar = {
      background = "#0B0022",
      active_tab = {
        bg_color = "#2B2042",
        fg_color = "#C0C0C0",
        intensity = "Normal",
        italic = false,
        strikethrough = false,
        underline = "None",
      },
      inactive_tab = {
        bg_color = "#1B1032",
        fg_color = "#808080",
        intensity = "Normal",
        italic = false,
        strikethrough = false,
        underline = "None",
      },
      inactive_tab_hover = {
        bg_color = "#3B3052",
        fg_color = "#909090",
        intensity = "Normal",
        italic = true,
        strikethrough = false,
        underline = "None",
      },
    },
  },

  
}

