name: Bug Report
description: File a bug/issue
title: 'bug: '
labels: [bug, triage]

# We cannot use nix-community/home-manager
# See https://github.com/dear-github/dear-github/issues/170
assignees: [rycee, berbiche, sumnerevans]

body:
- type: checkboxes
  attributes:
    label: Are you following the right branch?
    description: |
      You should follow the branch of Home Manager that corresponds to your
      version of Nixpkgs; see [the README](https://github.com/nix-community/home-manager#releases) for details.
    options:
    - label: My Nixpkgs and Home Manager versions are in sync
      required: true
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: |
      Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Issue description
    description: |
      Please describe the issue.

      For support and help please use the IRC channel #home-manager at irc.oftc.net or
      Matrix room <https://matrix.to/#/#hm:rycee.net> instead.
  validations:
    required: false
- type: textarea
  attributes:
    label: Maintainer CC
    description: |
      Please @ people who are in the `meta.maintainers` list of the offending module.
      If in doubt, check `git blame` for whoever last touched something.
  validations:
    required: false
- type: textarea
  id: system
  attributes:
    label: System information
    description: |
      Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
    render: markdown
  validations:
    required: true

