[[sec-release-23.11]]
== Release 23.11

This is the current unstable branch and the information in this section is therefore not final.

[[sec-release-23.11-highlights]]
=== Highlights

This release has the following notable changes:

* When using <<opt-programs.fish.enable>>, the setup code
for <<opt-home.sessionVariables>> is now translated
with https://github.com/bouk/babelfish[babelfish].
This should result in significantly faster shell startup times
but could theoretically break
if you have very complex bash expressions in a session variable.
Please report any issues you experience.

* The `.release` file in the Home Manager source tree
has been supplanted by `release.json`,
which contains more information about the branch.
If you have any external code reading this file,
please migrate to using `release.json` instead.
The `.release` file will be removed in 24.05.

[[sec-release-23.11-state-version-changes]]
=== State Version Changes

The state version in this release includes the changes below.
These changes are only active if the `home.stateVersion` option is set to "23.11" or later.

* Nothing, yet.
