[[sec-release-22.05]]
== Release 22.05

This is the current unstable branch and the information in this section is therefore not final.

[[sec-release-22.05-highlights]]
=== Highlights

:hm-weblate: https://hosted.weblate.org/projects/home-manager/

This release has the following notable changes:

* The `programs.waybar.settings.modules` option was removed.
Waybar modules should now be declared directly under `programs.waybar.settings`.

* Home Manager now partially support translation of texts into different languages.
Note, the support is quite limited at the moment.
Specifically, it only applies to parts of the system written in the Bash language,
such as the `home-manager` command line tool and the activation script.
+
If you would like to contribute to the translation effort
then you can do so through the {hm-weblate}[Home Manager Weblate project].

[[sec-release-22.05-state-version-changes]]
=== State Version Changes

The state version in this release includes the changes below.
These changes are only active if the `home.stateVersion` option is set to "22.05" or later.

* The <<opt-programs.waybar.settings>> option now allows defining modules directly under <<opt-programs.waybar.settings>>.
Defining modules under `programs.waybar.settings.modules` will now be an error.
For example,
+
[source,nix]
programs.waybar.settings.modules."custom/my-module" = { };
+
becomes
+
[source,nix]
programs.waybar.settings."custom/my-module" = { };

