{ lib }:

let
  generateGroup =
    name: value:
    let
      keys = builtins.attrNames value;
      attrKeys = builtins.filter (k: lib.hasPrefix "@" k) keys;
      childKeys = builtins.filter (k: !(lib.hasPrefix "@" k)) keys;

      attrs = lib.concatStrings (
        map (k: " ${builtins.substring 1 999 k}=\"${lib.escapeXML (toString value.${k})}\"") attrKeys
      );

      children = lib.concatStringsSep "\n" (map (k: "    ${generateGroup k value.${k}}") childKeys);
    in
    if children == "" then
      "<group id=\"${name}\"${attrs}/>"
    else
      "<group id=\"${name}\"${attrs}>\n${children}\n  </group>";

in
{
  # Render a settings attrset as a complete preferences.xml file.
  preferencesToXml =
    settings:
    lib.concatStringsSep "\n" [
      ''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>''
      "<!-- Generated by Home Manager — do not edit directly -->"
      ''<inkscape version="0.92.0+devel">''
      ''<group id="preferences">''
      (lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: value: "    ${generateGroup name value}") settings
      ))
      "</group>"
      "</inkscape>"
      ""
    ];
}
