{ config, lib, pkgs, ... }:

with lib;

{
  config = {
    programs.vifm = {
      enable = true;

      config = {
        set = [ "relativenumber" "vicmd=nvim" ];
        filetype = [ "*.pdf zathura %c %i &" "* xdg-open %c" ];
        map = [ "q ZQ" ];
        noremap = [ "gg ggj" ". za" ];
      };

      extraConfig = ''
        view
      '';
    };

    test.stubs.vifm = { };

    nmt.script = ''
      assertFileExists home-files/.config/vifm/vifmrc
      assertFileContent home-files/.config/vifm/vifmrc ${
        pkgs.writeText "vifmrc.expected" ''
          " Generated by Home Manager.
          " Refer to https://wiki.vifm.info/index.php/Configuration_model


          filetype *.pdf zathura %c %i &
          filetype * xdg-open %c
          map q ZQ
          noremap gg ggj
          noremap . za
          set relativenumber
          set vicmd=nvim
          view
        ''
      }
    '';
  };
}
