[[sec-release-19.09]]
== Release 19.09

The 19.09 release branch became the stable branch in October, 2019.

[[sec-release-19.09-highlights]]
=== Highlights

This release has the following notable changes:

* The `programs.firefox.enableGoogleTalk` and
  `programs.firefox.enableIcedTea` options are now deprecated
  and will only work if Firefox ESR 52.x is used.

* The `home-manager` tool now provides an `uninstall` sub-command that
  can be used to uninstall Home Manager, if used in the standalone
  mode. That is, not as a NixOS module.

[[sec-release-19.09-state-version-changes]]
=== State Version Changes

The state version in this release includes the changes below. These
changes are only active if the `home.stateVersion` option is set to
"19.09" or later.

* The <<opt-programs.firefox.package>> option now expects a wrapped
  Firefox package and defaults to `pkgs.firefox`.

* The options <<opt-home.keyboard.layout>> and
  <<opt-home.keyboard.variant>> now default to `null`, which indicates
  that the system value should be used.
