[[sec-release-20.03]]
== Release 20.03 (unreleased)

This is the current unstable branch and the information in this
section is therefore not final.

[[sec-release-20.03-highlights]]
=== Highlights

This release has the following notable changes:

* Assigning a list to the <<opt-home.file>>, <<opt-xdg.configFile>>,
and <<opt-xdg.dataFile>> options is now deprecated and will produce a
warning message if used. Specifically, if your configuration currently
contains something like
+
[source,nix]
----
home.file = [
  {
    target = ".config/foo.txt";
    text = "bar";
  }
]
----
+
then it should be updated to instead use the equivalent attribute set form
+
[source,nix]
----
home.file = {
  ".config/foo.txt".text = "bar";
}
----
+
Support for the list form will be removed in Home Manager version
20.09.

[[sec-release-20.03-state-version-changes]]
=== State Version Changes

The state version in this release includes the changes below. These
changes are only active if the `home.stateVersion` option is set to
"20.03" or later.

* The <<opt-programs.zsh.history.path>> option is no longer prepended
  by `$HOME`, which allows specifying absolute paths, for example,
  using the xdg module. Also, the default value is fixed to
  `$HOME/.zsh_history` and `dotDir` path is not prepended to it
  anymore.
