{
  lib,
  config,
  ...
}:
{
  programs.libreoffice = {
    enable = true;
    settings."/org.openoffice.Office.Common/Misc".ShowTipOfTheDay = false;
  };

  home.activation.loRegularConfig = lib.hm.dag.entryBefore [ "linkGeneration" ] ''
    echo "Hello, World!" > ${config.xdg.configHome}/libreoffice/4/user/registrymodifications.xcu
  '';

  nmt.script = ''
    assertLinkExists "home-files/.config/libreoffice/4/user/registrymodifications.xcu"
    assertFileRegex "home-files/.config/libreoffice/4/user/registrymodifications.xcu" "<!-- Generated by Home Manager. -->"
    assertFileRegex "home-files/.config/libreoffice/4/user/registrymodifications.xcu" "ooSetupLastVersion"
  '';
}
