{
  wayland.windowManager.hyprland = {
    enable = true;
    configType = "hyprlang";
    package = null;
    portalPackage = null;

    extraLuaFiles = {
      foo = "";
      "foo.lua" = "";
      hyprland = "";
    };
  };

  test.asserts.assertions.expected = [
    "wayland.windowManager.hyprland.extraLuaFiles cannot define hyprland.lua because it is generated by the Hyprland module."
    "wayland.windowManager.hyprland.extraLuaFiles contains entries that resolve to the same Lua file path."
  ];

  test.asserts.warnings.enable = false;
}
