on:
  push:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nix-community'
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "merge conflict"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 10000
